# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.run]
dependencies = ["checkf"]
command = "cargo"
args = ["run"]

[tasks.runw]
dependencies = ["checkf"]
command = "cargo"
args = ["run"]
watch = true

[tasks.ask-token]
script = '''
#!@duckscript

echo discord token:
discord_token = read

echo set ${discord_token} as current the discord token
set_env DISCORD_TOKEN ${discord_token}
'''
private = true

[tasks.docker-build]
command = "nix-build"
args = ["docker.nix"]

[tasks.docker-load]
script_runner = "@shell"
script = '''
docker load < result
'''

[tasks.docker-run]
condition = { env_set = ["DISCORD_TOKEN"] }
dependencies = ["ask-token"]
command = "docker"
args = [
  "run",
  "--name", "Bot",
  "--env", "DISCORD_TOKEN=${DISCORD_TOKEN}",
  "whirlsplash/bot"
]

# Build 'n' load
[tasks.bnl]
dependencies = ["docker-build", "docker-load"]

